/**
 *
 * Can show a tooltip over an element
 * Content of tooltip is the title attribute value of the element
 * copyright 2004 Laurent Jouanneau. http://ljouanneau.com/soft/javascript
 * release under LGPL Licence
 * works with dom2 compliance browser, and IE6. perhaps IE5 or IE4.. not Nestcape 4
 *
 * To use it :
 * 1.include this script on your page
 * 2.insert this element somewhere in your page
 *       <div id="tooltip"></div>
 * 3. style it in your CSS stylesheet (set color, background etc..). You must set
 * this two style too :
 *     div#tooltip { position:absolute; visibility:hidden; ... }
 * 4.the end. test it ! :-)
 *
 */


// create the tooltip object
function tooltip(){}

// setup properties of tooltip object
tooltip.id="tooltip";
tooltip.offsetx = 10;
tooltip.offsety = 10;

tooltip.snow = 0;
tooltip.tooltipElement=null;
tooltip.title_saved='';
tooltip.saveonmouseover=null;
tooltip.ie4 = (document.all)? true:false;		// check if ie4
tooltip.ie5 = false;
tooltip.bgcolor = "#FF0000";
tooltip.color = "#000000";

if(tooltip.ie4) tooltip.ie5 = (navigator.userAgent.indexOf('MSIE 5')>0 || navigator.userAgent.indexOf('MSIE 6')>0);
tooltip.dom2 = ((document.getElementById) && !(tooltip.ie4||tooltip.ie5))? true:false; // check the W3C DOM level2 compliance. ie4, ie5, ns4 are not dom level2 compliance !! grrrr >:-(


/**
* Open ToolTip. The title attribute of the htmlelement is the text of the tooltip
* Call this method on the mouseover event on your htmlelement
* ex :  <div id="myHtmlElement" onmouseover="tooltip.show(this)"...></div>
*/
tooltip.show = function (e,htmlelement) {
	this.affiche = 0;
   if ( this.ie4 || this.dom2 ) {
      // we save text of title attribute to avoid the showing of tooltip generated by browser
      text=htmlelement.getAttribute("title");
	  this.title_saved=text;
      htmlelement.setAttribute("title","");
      // Fond
      if( !htmlelement.getAttribute("tooltip_bgcolor")){
		this.bgcolor = '#FFEEC7';
	  }else{
		this.bgcolor = htmlelement.getAttribute("tooltip_bgcolor");
      }
      // Texte
      if( !htmlelement.getAttribute("tooltip_bgcolor")){
		this.color = '#000000';
	  }else{
	  	this.color = htmlelement.getAttribute("tooltip_color");
      }
   }
   
	if(this.dom2){
		this.tooltipElement = document.getElementById(this.id);
	}else if ( this.ie4 ) {
		this.tooltipElement = document.all[this.id].style;
	}

   if(text == '')	return;

	addEvent(document,'mousemove',this.mouseMove);

	
	if ( this.ie4 || this.dom2 ) {
   

		if(this.ie4) document.all[this.id].innerHTML = text;
		else if(this.dom2) document.getElementById(this.id).innerHTML=text;		

		if(this.ie4) {
			this.tooltipElement.visibility = "visible";
			this.tooltipElement.backgroundColor = this.bgcolor;
			this.tooltipElement.color = this.color;
		} else if(this.dom2) {
			this.tooltipElement.style.visibility = "visible";
			this.tooltipElement.style.backgroundColor = this.bgcolor;
			this.tooltipElement.style.color = this.color;
		}
		
   }
   
	affichediv3(e,'tooltip',10,5);
   return false;
}

tooltip.showLoading = function (htmlelement, text) {
	this.affiche = 0;
   if ( this.ie4 || this.dom2 ) {
      // Fond
      this.bgcolor = htmlelement.getAttribute("tooltip_bgcolor");
      // Texte
      this.color = htmlelement.getAttribute("tooltip_color");
   }
   
	if(this.dom2){
		this.tooltipElement = document.getElementById(this.id);
	}else if ( this.ie4 ) {
		this.tooltipElement = document.all[this.id].style;
	}

   if(text == '')	return;

	addEvent(document,'mousemove',this.mouseMove);

	
	if ( this.ie4 || this.dom2 ) {

		if(this.ie4) document.all[this.id].innerHTML = text;
		else if(this.dom2) document.getElementById(this.id).innerHTML = text;

		if(this.ie4) {
			this.tooltipElement.visibility = "visible";
			this.tooltipElement.backgroundColor = this.bgcolor;
			this.tooltipElement.color = this.color;
		} else if(this.dom2) {
			this.tooltipElement.style.visibility = "visible";
			this.tooltipElement.style.backgroundColor = this.bgcolor;
			this.tooltipElement.style.color = this.color;
		}
		
   }
   
	affichediv3(null,'tooltip',10,5);
   return false;
}
tooltip.setContent = function(htmlelement) {
	document.getElementById("tooltip").innerHTML = htmlelement;
}

/**
* hide tooltip
* call this method on the mouseout event of the html element
* ex : <div id="myHtmlElement" ... onmouseout="tooltip.hide(this)"></div>
*/
tooltip.hide = function (htmlelement) {
	if ( this.ie4 || this.dom2 ) {
		htmlelement.setAttribute("title",this.title_saved);
		//this.title_saved="";

		if(this.ie4) {
			if (this.tooltipElement) {
				this.tooltipElement.visibility = "hidden";
			}
		}
		else if(this.dom2) { 
			this.tooltipElement.style.visibility = "hidden";
		}
		removeEvent(document,'mousemove',this.mouseMove);
	}
}



// Moves the tooltip element
tooltip.mouseMove = function (e) {
   // we don't use "this", but tooltip because this method is assign to an event of document
   // and so is dreferenced
		affichediv3(e,'tooltip',8,12);
	return;
}

